### ISSUE TITLE
NavigationPage opening as modal always

### ISSUE THREAD

**Issue by davibittencourtome** [giuseppenovielli/XF-Prism-Full-Navigation-Example#1]
I've implemented this Prism masterDetail in my app, however any navigation I use with nameof(NavigationPage), is opening as modal, rather than stack browsing.

Do you have any idea what it might be? 

I'm browsing like this, as usual: 
`await NavigationService.NavigateAsync($"{nameof(NavigationPage)}/{nameof(TipsPage)}");`

Edit: 

Searching the community, I found an open issue in Prism [https://github.com/PrismLibrary/Prism/issues/2468], I thought it was an implementation issue on my part.
I will have to wait for the next version, continue with MasterDetailPage and go back to version 8.0.0.1909.

**Comment by DaviBittencourt** [comment]
using MasterDetailPage navigation occurs in stack normally, but with FlyoutPage the pages only open in modal.

**Comment by giuseppenovielli** [comment]
hi @davibittencourtome, yes, it seems to be a Prism 8.1 regression.
Downgrade to 8.0.0.1909 and wait bug fix there

https://github.com/PrismLibrary/Prism/issues/2468

**Comment by davibittencourtome** [comment]
Hi @giuseppenovielli, I've already downgrad, now it's wait. Thanks!

**Comment by giuseppenovielli** [comment]
@davibittencourtome i fixed this issue, please see code.
Now you can upgrade to Prism 8.1.

FlyoutPage.Flyout Page must use the same ViewModel of FlyoutPage.

https://github.com/giuseppenovielli/XF-Prism-Full-Navigation-Example/blob/514871a2cb2b903fd7836ad64c43415a34daea33/PrismFullNavigation/PrismFullNavigation/Views/MenuPage.xaml#L8
